apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-api-data
  namespace: rust-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
