# Wildcard cert for internal *.cl.tafu.casa in media namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cl-tafu-casa
  namespace: media
spec:
  secretName: wildcard-cl-tafu-casa-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "*.cl.tafu.casa"
