apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:UGbd18tbsatU5aBodMSrEq8QP3Pb5pTTPWIa95HIsOO1fKqV42LEvA==,iv:LKN2sLpAdBhfHjgzLK9xrfOLEe2ZXYKbtPdssDTOj9Y=,tag:zLtbjJd4yrerRZbmkTdAAg==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWjlqdVA1T0JEekh2d09F
            dG5UYUF5NXZWNTFDZDFNbUZ6Rll5RVA2U1U0Ckh3dEFENE1Bd1RDcmtHT1U3VjBp
            R3VmQkVmK1kzVG9MN3hJSGozUmxSdzgKLS0tIDFwZVJvRGVTVVRVZDBIOVRVNDNz
            T1R0OWxiaFpUdmo2SzJQUFJ5SnNRL3MK5YbJERiHk2W+ErZQ4GG/TksUu7bfs4Nr
            OjdE5Gdx+eoxvFp4ko1z4XKegpiboUgZxN4qhtXAoArU8RTHoRZpmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:42:41Z"
    mac: ENC[AES256_GCM,data:56jGyWaS7X8/TBKflR7sI8UzD3sdvcYxTOPrbjHirla0cXjaDuN+Wt5FlgfjIBWRejxdFrQvs1LSRua5A/zbZpDX26v8mbr4CTtJ3qY4lKO6askeicqUH/Qt0rUVJSoAh9zHCIVa0RBU7fify9GgU2pA+IgTgcWbwngNUtlc9tk=,iv:8fHmE+csrEwttQ1BQTj7YEwKo9KPABF0hjuS7QWaja0=,tag:1eWbQzgtwdv9gPn3siJWzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
