apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-secret
    namespace: filebrowser
type: Opaque
stringData:
    FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:YS9QwhwRdrPJ890F62/Vg9QNga7nI1ET,iv:3VJs69aQXRXL2M/elxFryQoAsg7oBOvhILiLaIKQeXU=,tag:hXxB5LQZwsYkbM7sWa5cfQ==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscXY1dzEvMkVaWnArc20r
            ZTc1Vjhad0k0M2NVUTh6VWUrU1hEL1F5YnpzCkxabE9FbDdBZDhjaGVCUHhUVFZC
            OVFoVGwyRHlsZkMzWkZYOWVnei9zK28KLS0tIG83QjMvRHgyRERvTmxXNWpxODBG
            UVRFQlREQ2JTU2ZaUkpJZnJQZ2JQVTQKhyMpv9pWF/kcKkYtzUbPtmcacfiXfkjZ
            6z5o66wh/2ZhFokWEjwmoq53o+1g07MvO3Wk51PtQs16neaLguz24w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T20:09:04Z"
    mac: ENC[AES256_GCM,data:+kViI6klE0agJDOnNPgPKtGacPc2kq9Uz6kWg+Ih4hY8B6QXJuizIUe0bw1J5QolrSeBU0mDmjlerlSPVJLPKpNhnl4eOU5JVcEnB6XjiPVyQv7gwrYyEwS+/nUZMpoGBF9SSljsUh60SrnqAy8nzjUtQm0/dE0D+NITGk1NDWU=,iv:AvV/YGhDqnps2Kf459ZP8i3n8MaW4h7ki1rNoUFwX9I=,tag:jXC+4+YmGe35MF2ExChnTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
