apiVersion: v1
kind: Secret
metadata:
    name: valheim-secret
    namespace: valheim
type: Opaque
stringData:
    PASSWORD: ENC[AES256_GCM,data:sXjZh1U=,iv:bgDYmlu/ssLw4a4YIooZRAyGHsr9NF2bauwxzQRcVVU=,tag:2OhM6VmQqXsEbNmBTf+RYQ==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR2NvcUxIa3pBbndMMHkr
            d1R0dU9KMDcrdWpUSXBNYnFweXZhQkEzS1FVCjQ3UHFtSVpQa25aTUlCWmJjZGpH
            VVdOU1BuRmVPK3ZPMHlsTEFnbUJsbjQKLS0tIEVBMlAwOEZtTytBWXQ5bFFUU0JO
            bzV5MEZvVGxyWWxYMExtQUNIc25pNVkKf0XoWYpuwPQBAv3czjEHtV/uUNzsveKS
            4SlBFinOoH/UhgTgSPn8YIlsq/ZJNZVfpodcbKpa5Q3hzsqiskiu9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T12:18:00Z"
    mac: ENC[AES256_GCM,data:iiwXlLPEdTUnOJHGPepEkB5VrnV3iR4Ow+WrtS5aGc+BCGS7VNCT4XP0DQ+9wPniW9s4NUgSCqFzNS8TFl4nvL49DQvbfi/t/Q/0CdS+XkhXADeK8pLHGG4iaVindYIG31ZohBfRF3ydbrLR+Eft/A2+Ta6kaYJPBLkotZ9eWXg=,iv:gc8SWi/kNAfblyWPzH8R29iCeqlWrMxlvCPhw9dE0tU=,tag:5bMgyzCTisFY64fN1ksmkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
