apiVersion: v1
kind: Secret
metadata:
    name: valheim-secret
    namespace: valheim
type: Opaque
stringData:
    PASSWORD: ENC[AES256_GCM,data:+PykJY2Bwl50iCk=,iv:dPTz20+jrIgEgh5dYCV5GzSKYZcw9UJQt6AQ7gb58rQ=,tag:jWYCFQ3a9QlDbKjdGdQxbw==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcWhXRW9wZkV5WnNtSXpp
            M1pGdFZoQXpHVnlHaGFybkVnV2gzb3ZoVG4wCmRyYjVSZDB6VjlyQVJWL0d6d0lX
            aFNxUUdmU1FQeFE0a2NVMDBuUTBNcXMKLS0tIGlFM0xCYmRwVEhKN2ZnTms3d2Ja
            bDN0WDAzK1daZHRhOEJYWkpVWDdtQ1UKBrnz6NwQqy08ojsKhNP5ireWIw5EHClb
            zTrMTl+gafimCnSA/0aYQcWEkEy4JetO7UbQiibmBLff/1DFNV+E7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T12:01:33Z"
    mac: ENC[AES256_GCM,data:CgbnOBi6pSY9mzj9rGt2gsmGNSVHiBqGGx2RS8nzfJXZwgVCjs+upARxG3ZdkakZrd3/AhJ7bDQxSUpEn1cnO3cf4Cef3KSflTk6dONt9m3A4FIi/JewH0AvFXIM5ukfwSANBqt3s43acALp/RZcZ7050xtd3g9f7Gi1wZTLOkY=,iv:1G72yVEc8X5gPzEFhu/B9hTlHrOv4T34750zprZpLL8=,tag:9+xrIJ6TjXx/5i0xXi9ciw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
