apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustplus-shop-helper-v2-data
  namespace: rustplus-shop-helper-v2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
