apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fitv2-data
  namespace: fitv2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
