apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-breeder-data
  namespace: rust-breeder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
