apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  secretName: longhorn-cl-tafu-casa-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - longhorn.cl.tafu.casa
