apiVersion: v1
kind: Secret
metadata:
    name: kag-passwords
    namespace: kag
type: Opaque
stringData:
    SV_PASSWORD: ENC[AES256_GCM,data:AfviTi2l,iv:MrkrHMf6YApsru72XHCFWPRk4nBFzxiRrCSz24CiGQ0=,tag:kEcwjVUa8Z8A74IQxNQKkw==,type:str]
    RCON_PASSWORD: ENC[AES256_GCM,data:EmgK7cak,iv:nz7AyMTpnhOP7cCyiz85nzKYYp796WwXrnhmBWruZNE=,tag:GtW6WPzUizHKgZ3cqVjeHg==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqY0c2L1ZDVm4rNmU0d092
            K1NKSTdOa1VuMzFtOXYweVU2bk85VWpMTVRjCmVrbU9kMzB0azdaUGFoUFl0RExp
            ck9lTWpyVndqVmIzZ3BZeUxWUWFCS2cKLS0tIGNxUVFGVUZoM1kvdlBGUnFKaVVL
            eDRCSytUMFpETWJTbnN2TUdOTUFZSHcK2QnG+p9gchkL4GBOBIIlML15dcIED1i2
            rBSBP2c/2k92b/pvBKSx1x6XWoIVZmm6BqG/0nupTmwgYW2bl1gRzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T17:29:29Z"
    mac: ENC[AES256_GCM,data:OkDqnwuIQ4Y9bjApWtgXWr4sdYvGuiG9tgWJYxXh5Us1Z2FyVJ9M/G8mCpMkP1lVkAlqTDu137gc8yKOyOifm9ISJnCCrIUlTgQkzaoxvkTa/zMoMGAscYqg7gKoD5nL00A1g1joP1aeokZ/HIBZAs3mRTG6BbYmW72C9RkegCk=,iv:Xo4EhL0he+gKm02pek4MWXqlJ8dAVRLq0z9xaRrvZos=,tag:p8PFTjVGIvylr1oqZnu71g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
