apiVersion: v1
kind: Service
metadata:
  name: kag
  namespace: kag
spec:
  type: ClusterIP
  selector:
    app: kag
  ports:
    - name: game-tcp
      port: 50301
      targetPort: 50301
      protocol: TCP
    - name: game-udp
      port: 50301
      targetPort: 50301
      protocol: UDP
