apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shorturl-data
  namespace: shorturl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
