# JWT_SECRET for ConvertX (SOPS-encrypted).
apiVersion: v1
kind: Secret
metadata:
    name: convertx-secret
    namespace: convertx
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:ALI6+DSHmVzTDYUNi4D5dmODGCLP2dm65EWAyYHYHOLX0D3CHjHRKQxMQUIaCC10ywGe62TNXRthNiisSZcFBg==,iv:puu4AGv/+0ztxFHoCxP4QTv8C18pscL5FGnrdFMNeaM=,tag:O1lbJhW2TLJMEdRqmL+FLw==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVFE2NHQydlB6cnAzcENa
            cTgzcEpVdGx1eWJvaWduQjdpOFllNWhPY2pFClk5a05ualNoU3F2TldRK3loVitu
            QW9kWGV6dkpIT25taW92alhIT3UxeTQKLS0tIEhpeHRMYUFiZWVueXpMZGlSb1o2
            NVBPbERXaWlybHJaTGtwbFRlNU5jdW8K6EYwKdTPjcF+3J9YVQa0R1W9WvC+5MbC
            Ad9zG2R9cgPSZxfI5h5JTRKK0dOrXFNTCRcy6A3+G1NdcpPfDnBbDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T14:28:39Z"
    mac: ENC[AES256_GCM,data:F4xnTeFdZaobYud7MhxQ00nZofPF0okCojfLRCp02FhtAbczKC/cOyVoGTwVW2WABRcYDmLcJe+uOCfrjUh9MCYyh+SyzXUagM4e/ZR30NJhV8GNGhCkwohuRB02iiMMhk3v/I8u/5AHu7qtzdN7ZEktMoJcDmTA8f1DB2iqXzQ=,iv:sBRd0jWntI1dyLcS/uWIKNbzgXpuz2ukR17qJTBEpZE=,tag:+knXnidoL2pvQ4wH4zvT0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
