apiVersion: v1
kind: Secret
metadata:
    name: ghcr-registry-webplayer
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ujAigw45UWAQssAbqZzhlHVBrLJW9Uyv7d5CGnMB1ibRZHEdo9aH3gCX3VXTLlGy/8+vf1cIuJ5WFn2RTaFk/eO5sID5WUlrt8jzfaqXo5nkd3yQrogGMo+4kk5k3Z00mI1d9w516oPFa3DrdDwBataAjfNHNs9YsMP3TurhahLnuM/a0snrEx/Jm7mTSFTzJOfMm+AagvPdhxvEIb7excywPv+oeV6Qe9IQ4/LzCrK4ET4onn/YUxFP4emA8UhhuCf9bowHyA==,iv:fqELZL2xdqwCAZqMXrAkoSRhhC46PatQZmDKpxadkKk=,tag:f6hyVGonfXuM0SWle0dHJg==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkckltbUdmM1RxL3piKzNJ
            cWRHemt5QTByaUZDQUpEelhzdktyTFRxOGhzCmxEcFgrNUVmR2NQKzNtcDZuN01T
            Y1RFSVpHTDZQajJJV083NU44ZFFLb2cKLS0tIFovWDIvTW5qSmNkU0ppMk9vMW9v
            a1oreTRIeFQzZTJQOVNMdWFCUUdtMkUK5xCz4mtGL2229ifxsFFgkSKTfa9C2NzH
            RGV/f+OEvVk8VC4/aTz6r9orsHTKE/IowDLjg+iHvTnI3+uGz0PU7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T23:59:59Z"
    mac: ENC[AES256_GCM,data:D0QAyCc2dj+pfZdkjJVZdmkwtA0zW5fXTTbNEwhpBFe2p7rFWJKSsmy29zbjFks48kqwVWHCxwTTwWflo1CkY+83zQZB3/Vn6CCNUk4h55F69xcmynIm0TRm6aQJ7dlt3Pq4li03q6VoB+MXGtYYaAjNvI7oBKYgQKux1T1Nmvw=,iv:ytaC3jHQD6XZ8sGNsOWZ0lU8yIyOL+WBdqLP8fcCdnU=,tag:2xNcph/pe/8rM/+R/Ko3kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
