apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: kag
  namespace: flux-system
spec:
  image: ghcr.io/nerif-tafu/kag-dedicatedserver
  interval: 5m
  secretRef:
    name: ghcr-registry-secret
