apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: microbin
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: microbin
  policy:
    semver:
      range: ">=2.0.0"
