apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: rustplus-shop-helper-v2
  namespace: flux-system
spec:
  image: ghcr.io/nerif-tafu/rustplus-shop-helper-v2
  interval: 1m
  secretRef:
    name: ghcr-registry-secret
