apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipe-dreams-data
  namespace: pipe-dreams
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
