apiVersion: v1
kind: Secret
metadata:
    name: proxmox
    namespace: proxmox
type: Opaque
stringData:
    PASSWORD: ENC[AES256_GCM,data:jeD7bHzMfzAY/i3CKc+UT56g6sQp8ZMcjAqQfRIqGVk=,iv:obJVh+QLvhY3NaJKuL7WNEnB8GHdR/K0d2pyOpvbkds=,tag:lMCe6zl3eglySCfdN8VV0w==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaUpxTWNFSW45ZGlQb0ZN
            SjdKK25XZWdKMkhvOTFMb1hpUlByZGR6S0ZrCkcycXpsREFtWGhTbmVGR2ljalE4
            UnRoUURrcnhZOGNqK1h6QWVQWnBMZlkKLS0tIEpnOVpEbnVnK1ZNajBISjBvU3Uw
            VzhEbHlKV1ozZnFnbnRGRW1QRk5sN0kKTa9b0IOC9ZusKLKGoFWEQF+ka0ZLti1p
            vbqur/VId0QjTm4TvgbBfUOzQMTS49ucnC5jBLaguI8efyxazo3KNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T01:20:42Z"
    mac: ENC[AES256_GCM,data:zQr/nxfDA5nil8RX3tkaVKLrCQ7bezwozIAqUm8JhdNgpVFNRyPwkpxyLCqjxslNWcOE6bLNg/THUqwsv+tE60i8r5dxH59ppE1jZ2HmoaylH/PGkJ73OgjTHEqU99lU0rgWHNfGtlJL8gE6PFbIX8rNiJcTlBGLwaisZrFaNfE=,iv:9+PLy0I47cSKuAgoGGMzSlfa9Io0vr3BXEggfRHRgWs=,tag:n3p97lvvNyc6WyieLIt0ww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
