apiVersion: v1
kind: Secret
metadata:
    name: git-credentials
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:BPrxsVrJJUmmBA==,iv:KbXwedSoG/6yOivOA0Tx8LHl3kRgAaYp5yh2DPOlta0=,tag:MCo4bdFho//e84dQbReP3Q==,type:str]
    password: ENC[AES256_GCM,data:bBNBLOMgV4SHoMuEPsALv1JIsbwrTMNCgAL2HEACTp9fw/GRC5h7uw==,iv:GjuUKvlKJKK70Dbdn+klC1ITneJg1nA+t4WOue/374E=,tag:KG5dyyOJQ6XmNvAExseEDA==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VTQ1dWgxaUFyWk9YU3Aw
            SC8vMlF6R1liUWczN1k1QzRpQmxtK2FJS0NzCk5ZU3J3Mzd6NHpzN1lYSUYwVlhK
            SXQ1WXMyY2tVa0REZUI3ODlTMyt3ZTgKLS0tIDFKREJuVEx3R3k3d0dlU1dyZDg5
            Wmt2Z1g4emxZYVplcnFnVVpnZ09pamsK910S12qzXdCDoKOfPk9WbvuAUm+NZoyo
            y+6XA7qIXXCB2vIaFOcEAjxDKPhhXA/94edooFaTGz9x7c5egPDAOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T00:31:51Z"
    mac: ENC[AES256_GCM,data:sUrctXvLx3qJ+5HvBAIjLq90dwbVT1qVBAJnXON+KmD3FSzGYad1qY9olFU3dBhCo6l08hRCV60o7BS49mfX99NKoZVU29wLHfwHS/ZCwsp63PLbiV61ouKHrr3GNJiMqHvBx8bLvfmxHxgKSkQhDel/aJ0f1UgmsizaQN+kqb8=,iv:hdPP0aH0jnLVsn/FlQBKhgrhaSiKECvRPuHqniBNlmA=,tag:6lhZJmR71a9MA0gVQxCbZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
