apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-plus-provider-data
  namespace: rust-plus-provider
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
