apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk
  namespace: helpdesk
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: helpdesk
  template:
    metadata:
      labels:
        app: helpdesk
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: helpdesk
          image: ghcr.io/nerif-tafu/helpdesk:1.2.0 # {"$imagepolicy": "flux-system:helpdesk"}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
          envFrom:
            - secretRef:
                name: helpdesk-env
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: helpdesk-data
