apiVersion: v1
kind: Secret
metadata:
    name: helpdesk-env
    namespace: helpdesk
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:X/FjVUc2BwM=,iv:q4HkxbSkIYZvtMaY/yPujvf4mvXcm5bmYIGYMFqymWk=,tag:VIokgfg4tXGkFshYccPZDQ==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:PJeIT94FTgdfdnMEXOCqSvMJhTNPi6tcN+4YpouIDULvtB0xlnJx5j7mlqXJS6SLTWVYPQlAv3KyO7P8wDkT7A==,iv:B9yHuQYwNLkl0kRcsavlouN+kAjfj9Q9alBADHJhB2M=,tag:HnYG1M4YTfYeWT1Don26Kw==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMDlHMy9vZEFrZmJLMTBR
            RGdlOUE1WGk2elJxRS81MnJXb2hyMEczS0M4ClhhOHg1bWlFTU40aWFKZmt2bjNp
            d0x4WlptSjROR3RwTFFUM1ptNEtRNWcKLS0tIFQ5bWora0hzaUtOc1dxVnBrQTh0
            R2NQci9FZmI4cUlXb0VCOThJWml3SDQKxeUHfyrKqy9ZlxedM0cpX4UTIr/xBrXQ
            tdvcYh0nJaBRX77pwz1n92kwYCKfgJ2X41OLzBrSz/6dWapORZzabA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T22:00:18Z"
    mac: ENC[AES256_GCM,data:lC7dC5i45iWc3MZZccEod2SyBDJgqbvki+2j7Leb/GL6Mny6z1+GCS/7lVckbjaES+azBnqHDhw5yTPcy/9H0KJWTcBfp1HWlzVkwk3O0TBLf1J7zxK2dGqjtYPa5gQxfFVeUwzUtwNrF+MNz9Q9ScQkX3xVFLoccSKDw811W9c=,iv:GngfGZTN6S1j7bdWwityGPPS6tzEMlkabp/ksXvV+Wk=,tag:ZgMMxI1++PJtJ9cBRZD7rA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
