apiVersion: v1
kind: Secret
metadata:
    name: helpdesk-env
    namespace: helpdesk
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:YzzuWvotUg==,iv:bv53+k/0shk1Sd8/Z90Ny+nCmOa0QJCswZ3nBZRAWj0=,tag:p2Q2LxZvT8h+pJqzdKdk6w==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:PJeIT94FTgdfdnMEXOCqSvMJhTNPi6tcN+4YpouIDULvtB0xlnJx5j7mlqXJS6SLTWVYPQlAv3KyO7P8wDkT7A==,iv:B9yHuQYwNLkl0kRcsavlouN+kAjfj9Q9alBADHJhB2M=,tag:HnYG1M4YTfYeWT1Don26Kw==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMDlHMy9vZEFrZmJLMTBR
            RGdlOUE1WGk2elJxRS81MnJXb2hyMEczS0M4ClhhOHg1bWlFTU40aWFKZmt2bjNp
            d0x4WlptSjROR3RwTFFUM1ptNEtRNWcKLS0tIFQ5bWora0hzaUtOc1dxVnBrQTh0
            R2NQci9FZmI4cUlXb0VCOThJWml3SDQKxeUHfyrKqy9ZlxedM0cpX4UTIr/xBrXQ
            tdvcYh0nJaBRX77pwz1n92kwYCKfgJ2X41OLzBrSz/6dWapORZzabA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T22:03:27Z"
    mac: ENC[AES256_GCM,data:HOhdLbx/TPy+xVkikVKD7nT40dJ4XitoIt59p3MxTiTDv5dWK4u4lpnhpYgYNUghowH7P/W2nFZxiUICiM9CnKT0RnqHTiLFsosNEmdnbsF1gzFEAYmptco0Y+NqRmlUFdUflWNeCGgKGr+r7j1y7ufUROWYUPypR391/O/OKYI=,iv:mZwbVj0SG0w5FpZ3o/HW+Nh/NJ4+iL+WDmjVhuRvO6Y=,tag:oVtM3SniKLWFmL4MjeIj7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
