apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helpdesk-data
  namespace: helpdesk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
