# Flux notification-controller Discord Provider webhook -> #homelab-gitops
# The key MUST be named `address`; that is what the Provider's secretRef reads.
apiVersion: v1
kind: Secret
metadata:
    name: discord-gitops-webhook
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:eS2l+JNC6FOnkwlfESWwxKqXdjWRI7ECYItK0KhP/gsXhWNV8wVShDLx/pSmPV/eRymeZMNnyKE9Xeaky8IKTKnOI3lQ62NsJU7lVOV94twDzKi9p1WiNNVKY0j/MnTfktFhmk5csnh7WfvT0qZBw7U4314vMokxIA==,iv:lhfS0otPyRhXMJevTmFS/pAxCrmtxa2DKPOoUV89Kbw=,tag:Gzg6hDUOK1olsMZZen0tkw==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYktlS2NNZ0Z3Vzd3Y3h6
            cjlBTDNDK0xKL09JdzNmcmRxTlhmOGh2MmhFCjlwWW5YelBhTldSd3FETUEwZlBl
            NWNxT2s0ZHVQS1dvRDlacmR5RlRkeHcKLS0tIFBKMG42c2ovNkFLbnB5blRqNG1a
            OCt4ck1QUUFlWEtlTVQxQXh2bmJtMWsKRpsHHpfY6HvNg+B7wsoPsZgzazMdM5g2
            P+SK5lnzxTOoG7a+p17bxnxU+FiEkBCdT4mjY3WcIYtNePyT06q15w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T17:43:39Z"
    mac: ENC[AES256_GCM,data:H6+i63KWvSzhsQ6ZTjxWNxTw8qpcKQX4m1Vh8m9WKh8fwR/QdVA8j3bKFuF4gcsTHYsHmc548ltMDpuSETLgGNZzUFohAdcimm0da0vaPChL6DdKQyXgl3x84694YAxijVtUqpTh6MJus3v8PytwvYKMmZFfZiz9QB1muFJ728I=,iv:8aypG0dlCz9tuQls+HXbNpxOss+PjgNFiHtyUKgGChM=,tag:043TJehwaHLQq8RYtX9cvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
