apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - discord-gitops-webhook-secret.yaml
  - provider-discord-gitops.yaml
  - alert-gitops-errors.yaml
  - alert-image-updates.yaml
  - provider-alertmanager.yaml
  - alert-gitops-errors-alertmanager.yaml
