apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-booter-data
  namespace: rust-booter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
