apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lavalink-data
  namespace: vocard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
