apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vocard-db-data
  namespace: vocard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
