apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ontime-dsm-data
  namespace: ontime
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
