apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-config
  namespace: tandem
data:
  livekit.yaml: |
    port: 7880
    rtc:
      tcp_port: 7881
      port_range_start: 50000
      port_range_end: 50060
      use_external_ip: true
      allow_tcp_fallback: true
    turn:
      enabled: true
      domain: livekit.tafu.casa
      udp_port: 3478
