apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandem-redis-data
  namespace: tandem
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
