apiVersion: v1
kind: Secret
metadata:
    name: tandem-env
    namespace: tandem
type: Opaque
stringData:
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:lt6n9D6hvDUpB4POQQl4sdlunw==,iv:ACuWWPbDTDstLBcW+1rdQJtHR7j551dP0/wcJwTckCs=,tag:BrIuBRdGEBVmW4RXo/614Q==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:KyRnoYspN9TTaaXHWj4zCigTtUvq5gnNRUtClsnRf4JyG+wctrrF8anVehEtDtsGYXlp+cBOT6mGlSobvQ+sTw==,iv:OTl4CUwDUyJRU9QN6K6YC4mbgAymGJgoIgzcrQ/SHag=,tag:mXXgryk3emLH8PdYOmaC2A==,type:str]
    LIVEKIT_KEYS: ENC[AES256_GCM,data:FCBBISIGP/eAUreID3/PEOAGn7QnsvG/eg8ZeQhp+Mx9b3hhrFZBOsofqWxPSCrKLZ+CDr3uIryS7jPujrxA6S9/ZnCOmxLmfqzPAkcy6pG3W3ZUWg==,iv:ZIrFFX/XXLHbYgPmHrY5OiGgO3AgcAejLAUavsGw6kE=,tag:KjynivcgSLtGJ6BQn3B5cw==,type:str]
    LIVEKIT_NODE_IP: ENC[AES256_GCM,data:flVzqzD0MbGE8rcfBA==,iv:APHaOhgiqM3VcZmpNVAmT1Qq075Od6bIbFXVihPcD0M=,tag:OloqsWm79KwsiRseTsMTEA==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS2NSMVdwb3dTUElGbDMw
            K3BmTlFOVi9OTUw5bWwrMzZOU1F0c09HTWxjCmZuREtQY0swRUZ4dG9ucFc0SEpD
            SXdtbzVZaVpacnIwK3NJMzF5YUg5L0EKLS0tIFlLR084UG11VnEwNjZrY0RKbkEw
            WXBKR3N3dk0vQlZ6bTFneGkySEdpd3MKaJJFkyNSEFiY683P7e3UQtRYO+fivH2J
            Ohk7QVEScL2JwHwbpyWaihsRZv9+ps8QQyuD1FZpcPss4rOEa48iHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T02:06:23Z"
    mac: ENC[AES256_GCM,data:y8LFCt2ac+jW7NzT3rrU0aYSEOcMYc/JNHbnDS1k/PIuHFDMCK7L4r6iaoxhznVOTzHCPU9Ciyza9fcHE3+8HxrnCbmMmdhKrHS00fkSm4U0k7tMZfS+RUSz5gqsCwTW+bZUXWFW+IFvwZ6Nmb4zXTcP1Mxur5yL8CjP82NaE60=,iv:T/AG/omq3OTv1unbVHChYiXjLIGXuK9xi8HIW7uo5f4=,tag:SR+iwv3FSowk3I2SCfbxGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
