apiVersion: v1
kind: Secret
metadata:
    name: tandem-env
    namespace: tandem
type: Opaque
stringData:
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:lt6n9D6hvDUpB4POQQl4sdlunw==,iv:ACuWWPbDTDstLBcW+1rdQJtHR7j551dP0/wcJwTckCs=,tag:BrIuBRdGEBVmW4RXo/614Q==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:KyRnoYspN9TTaaXHWj4zCigTtUvq5gnNRUtClsnRf4JyG+wctrrF8anVehEtDtsGYXlp+cBOT6mGlSobvQ+sTw==,iv:OTl4CUwDUyJRU9QN6K6YC4mbgAymGJgoIgzcrQ/SHag=,tag:mXXgryk3emLH8PdYOmaC2A==,type:str]
    LIVEKIT_KEYS: ENC[AES256_GCM,data:spsvS6AMctaHxVRJvCxEJ0oIyffLVqU+sT/gEKirNMzK5bhzmEjX1iLlGtkOvXrAobJvhNlk29WOX5TxSHLj2/Y=,iv:skwZcEvmbDHbukBkzoYGDQ8Nx+D4gYASizWH6FEDs+0=,tag:uGNQCthQoVccMklQrTwWPQ==,type:str]
    LIVEKIT_NODE_IP: ENC[AES256_GCM,data:u6stEdARTyH57SX3L+A=,iv:Zs9ClkgQYFlRA0GzOMpTHExtFWS0tKLpBLVw/mTyal4=,tag:DWlrd1Er2dG1NDIG00mJTQ==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS2NSMVdwb3dTUElGbDMw
            K3BmTlFOVi9OTUw5bWwrMzZOU1F0c09HTWxjCmZuREtQY0swRUZ4dG9ucFc0SEpD
            SXdtbzVZaVpacnIwK3NJMzF5YUg5L0EKLS0tIFlLR084UG11VnEwNjZrY0RKbkEw
            WXBKR3N3dk0vQlZ6bTFneGkySEdpd3MKaJJFkyNSEFiY683P7e3UQtRYO+fivH2J
            Ohk7QVEScL2JwHwbpyWaihsRZv9+ps8QQyuD1FZpcPss4rOEa48iHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T02:16:15Z"
    mac: ENC[AES256_GCM,data:TDEW8l9B172zgnIQhEoDzUBZ/kGP+MzxfImjb8VDjcEXx5L9ed6lbo2q0tmBZQLxbTd2/xKAde6kx3gYqKBMoJP7H/vWOn/oB412HmAIkycCHFBEGzP80/uaCCZyihC67be72YB3x3uG4l2M00iqwmEaJgnJ0rkgvYxmTuQE+Q0=,iv:fENzgejthjh9RzGH4XVogdzkn2YQAXiOFRgAfcq5DqI=,tag:KrBwVfJAL+yDoc25s+JT5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
