apiVersion: v1
kind: Secret
metadata:
    name: tandem-env
    namespace: tandem
type: Opaque
stringData:
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:lt6n9D6hvDUpB4POQQl4sdlunw==,iv:ACuWWPbDTDstLBcW+1rdQJtHR7j551dP0/wcJwTckCs=,tag:BrIuBRdGEBVmW4RXo/614Q==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:KyRnoYspN9TTaaXHWj4zCigTtUvq5gnNRUtClsnRf4JyG+wctrrF8anVehEtDtsGYXlp+cBOT6mGlSobvQ+sTw==,iv:OTl4CUwDUyJRU9QN6K6YC4mbgAymGJgoIgzcrQ/SHag=,tag:mXXgryk3emLH8PdYOmaC2A==,type:str]
    LIVEKIT_KEYS: ENC[AES256_GCM,data:FCBBISIGP/eAUreID3/PEOAGn7QnsvG/eg8ZeQhp+Mx9b3hhrFZBOsofqWxPSCrKLZ+CDr3uIryS7jPujrxA6S9/ZnCOmxLmfqzPAkcy6pG3W3ZUWg==,iv:ZIrFFX/XXLHbYgPmHrY5OiGgO3AgcAejLAUavsGw6kE=,tag:KjynivcgSLtGJ6BQn3B5cw==,type:str]
    LIVEKIT_NODE_IP: ENC[AES256_GCM,data:u6stEdARTyH57SX3L+A=,iv:Zs9ClkgQYFlRA0GzOMpTHExtFWS0tKLpBLVw/mTyal4=,tag:DWlrd1Er2dG1NDIG00mJTQ==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS2NSMVdwb3dTUElGbDMw
            K3BmTlFOVi9OTUw5bWwrMzZOU1F0c09HTWxjCmZuREtQY0swRUZ4dG9ucFc0SEpD
            SXdtbzVZaVpacnIwK3NJMzF5YUg5L0EKLS0tIFlLR084UG11VnEwNjZrY0RKbkEw
            WXBKR3N3dk0vQlZ6bTFneGkySEdpd3MKaJJFkyNSEFiY683P7e3UQtRYO+fivH2J
            Ohk7QVEScL2JwHwbpyWaihsRZv9+ps8QQyuD1FZpcPss4rOEa48iHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T13:15:18Z"
    mac: ENC[AES256_GCM,data:/5Se9o8aRLRt39ETweW8K1hT+AGhiTMx0s4iCxTy3pU7r9cEZkInjC8+japK+ifIaHBYau6m56w1tHu02ESWN30i7DmKTxtcbNnj4RaB5KZbF0ywjWCwlLzmXiHgoV6WXulIVdZ/tSpv4FLRCJ9fxZZeFoaBwyu56foxs2Rc5oY=,iv:d7yDCWbjKjS8hjWLIpvrQkXaL0lTOTu86QIkYM1kEtw=,tag:hqjLUPMs7v7Dab4HN+qXoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
