apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scholarsome
  namespace: scholarsome
spec:
  secretName: scholarsome-cl-tafu-casa-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - spanish.cl.tafu.casa
