apiVersion: v1
kind: Service
metadata:
  name: scholarsome
  namespace: scholarsome
spec:
  type: ClusterIP
  selector:
    app: scholarsome
  ports:
    - name: http
      port: 80
      targetPort: 3000
