apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: fitteef
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:lR5y4luc5nwLwUes/lc5JaUPV8RAo1bq3lFaZNYO9Pd677r3/sof1iXU1zVJi3RlinKSxPZmNCdsPQ+XZXBU69t4j9KxiJcNTDJK8fOvY0ta1vz3Fcqdbzbu+1jnmAKfvjnEgfKesgY+GV2yMV5PeErJ7fWkgoR67X4se4+jHLZcVgfB89HDN+ZISOds6or6PTnzuCDLcp71Fjq+nNCcxrLxfOt07oedhFyREweKk/4Ecj/B,iv:lb+j1wygfV9G+aq41j1Z7qlphHZigCm3BJROqA37Q9E=,tag:0WAzJ8yIG8+MpJUD0Tl+hA==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLejV3WFB0V25DcGx6M0Vv
            M2E3N0NsNFQ2djNOcWFVVjNMa2tpWGR6Um1vCmVuMDhWeENla2Y1NGEzc24xdVJX
            NnF5bWZnZjRhc05TeGV4UHZDcENHdU0KLS0tIG1FYzI0NjhPcW0wdG8yTVRRNTlT
            ZkR5SkU5OGxVMDNJNDJsWFVHM2czOG8KGl2XtjxQTpF2/BmhYAcyDRSE2MLy136g
            DFJL4q0MFIK/FZJDGEgeJIu9BXt67+BSBj9Yz2lJuP66uLstDdd/QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T20:11:38Z"
    mac: ENC[AES256_GCM,data:mZJgJfrL+8jhyO+yd3u+yr7vGErc1/1oiKeaSUVjh9MApvEZR8E47rGaUGHLcohEJhELxUZ7IkTgGw30IiZG52JY//eufXFQpFG67+euCOVqDufStEsgv48v8wiXTKwjq1e2P1FtDWiyqA0OpgoPpa8uJkS3DSnU4HO6kpRI6g8=,iv:h4CHUSJzPl5EmELGzgVYD8MQI8hR7ibTmWAD+LGgFqo=,tag:Iod0XaWGUAMwnS26mOst/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
