apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tafu-casa-data
  namespace: tafu-casa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
