apiVersion: v1
kind: Secret
metadata:
    name: tafu-casa-secret
    namespace: tafu-casa
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:IKkdlIq6RUAjRt9irIeLdD/C2RM7sJM4rNP5veN8ukR+bfVttoiczQLUhdU=,iv:FL4pCFt8jYL4qvISe21dpFcpD6TMdCP1nf47LQOjA78=,tag:05kzrS6dC+VjpYTqgH+NnQ==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSFdqOC82c040OUY0WnNz
            bGRXMFpyem1DQVU4OExDVSttU1FpQWNvdkdNCis5aGtsRkxOaWI1MGdrazBEajgv
            S3p2U00wRSsxRm55aytpaks3bUhOZ1UKLS0tIDFYN2k1QklHVWxmTUlZQVpXUUta
            ZVExYmJnRUJOaDRIU2RkRTBGY1d1WkEK7xD8by/on6QyW06WPTGvLigoerUbbpWp
            b1ZfSmy0leL8nF+QvysHNb6ZqI5LBVBeYtjZGD/Pij4dONVz2Uu3VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T11:05:00Z"
    mac: ENC[AES256_GCM,data:bcG/9TTqPl/dhl4RbOeYZz+YIiMxQpQPbMxgj0+3dA6CrpzhGDxvHuTZawYiqB4Obp9m7FfJ36mv9qarsvxANr9wXf8UqDJTVSwB5OekAgTm09xZCNVB+qNY8udiByfJkZjlux/jTf0pe5dlk4lT9HkR11L/rGSNEu8UG6wa/MY=,iv:fbcvm/VfUlsz/v5FdiHXjofo/LWkX8Yz+2gfsmMPN0A=,tag:lYmAnqujDCm6xsW+Z9krwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
