apiVersion: v1
kind: Secret
metadata:
    name: opengist-secret
    namespace: opengist
type: Opaque
stringData:
    OG_SECRET_KEY: ENC[AES256_GCM,data:NfaoaKbzqc74h+d6Des3Rfkx2Z//Lb5xP/H8ZhYbRV0kG4uGG6P/kOn8RigPx25K8xmE58XndhRYBTcMkkCk7w==,iv:U/PQdEFETylu9zFN+LNLlTvMV3Qbyvkr4kJz+92biCw=,tag:PJROQHxDxOehv31m7CenWA==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZTJGYXM5b0RkWXpabndY
            dGtNYjkwa1Z2c1lrdjFSbDRaZDg3aS9RakNrCnozZlZoUHNVOS8zL2xvU1NOSWNN
            OHhoS2xRR29jZHFXajVPNmlHUS80TXcKLS0tIGRmYXJvN3VVT1haR3J4bVJyU1Za
            cThCajN0TzYrMVVlbzdndUR1VjAvam8KQdSVz5sEfK0QoMOib9k4ON9YfsytXihY
            tWvsTFAeM2TlPmPNDyqODUZorz4Ax1nABJYbrRArbWW4gIbeE1CIjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T19:37:38Z"
    mac: ENC[AES256_GCM,data:5m/XlQeRUHwfJgWGdcNMkUwRwjbGJEc3qqNtk/Z1s1K9ISiv1IM5Bjs/WsDyTGUJ/umx4N/O6Me/aO9CIrHz6KL8nfBX4/PgC6kmeKCjcL65WGHLy29ukkZKPsE+WuKs26o1HP6Uafl9hwFHVHA0HOmRLtyS6AF5/aSfKZKSasQ=,iv:JOjZx8G72i3k18s1zUGpurB/SnBlAqK/Joi5HhknQFA=,tag:RF9CJ6CNFsexH0quUJU3Kw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
