apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: ClusterIP
  selector:
    app: minecraft
  ports:
    - name: game
      port: 25565
      targetPort: 25565
      protocol: TCP
