apiVersion: apps/v1
kind: Deployment
metadata:
  name: webplayer
  namespace: webplayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webplayer
  template:
    metadata:
      labels:
        app: webplayer
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: webplayer
          image: ghcr.io/throwmyaway1038471/webplayer:1.0.2 # {"$imagepolicy": "flux-system:webplayer"}
          env:
            - name: ALLOWED_HOSTS
              value: "webplayer.cl.tafu.casa"
          ports:
            - containerPort: 5173
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: webplayer-data
