apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: webplayer
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ZawnUSodFrxBepHwr4Kl8md2JBJoU9a5Hn10RMuu0eVR8orm6z+2yNPsLjC1uuHuqSzE1W1dkMEVGFGAOaPWOEI8wrTC1WHVUT2Nf2ACd5TjftYK5vZ/bR53D1vuSfr5pJZfL/VTn27u4ARPWC/bYyoJeGr6OryPJHiqOFIUe/w24rYeyInuhj27NuTVMD6AhWkoYZbJhLRNq447iNRm521DZ3AhCuTxujPtNVmjVzmQJ6Nf9OSSTiU74Oh+c21KL6CJseoTlw==,iv:QblJH5CQ1ryDcuUL7wpT05BXB11t+gmP/cIYioWvfIQ=,tag:vJmpw0LXTRIriRnIYjlF4w==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOG1JQXgrMG1SdmZuYitY
            MzhwSHFXSjZFbjBhTVllQzBZeUxiOHdyRFYwClY0ODNraXdieHI0SVRyNG5Lb1dS
            bXVCSWR3ZlhOdkhqZVduakdPc2xad28KLS0tIGJwQ1pnSHRnL01TbjRMQ1dNd3F0
            VS9EWmhzMFFBZVNOZUFibEFGY1UyK2cKz8WCb24lWAHNlgp3Eh+xmtB8kDiJ7KoY
            ySHgR6j5d4IwESjJkg3pXwip+7a9afdDzhl+b17oTjr9uDhDVxJN3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T23:32:10Z"
    mac: ENC[AES256_GCM,data:mAXL0cVcmK0K99xV/JyiVkyfxBxRuEsEuZmaHVlZ8Xx2a/2uADDgMomP2uxvuTTMOmhI+/5wGNGBhXbFM0yx8GBGAxWpAJT8QrTgoNYBTuy1AT0FTr1MMjlJbdfldpFdbvebiXS1riKzAa8VTCcSd1BwwpgcNFSAmfTmK5ZJ1hQ=,iv:x+aB3U+NuO3Pg0X840zGRtgAy0mlpc+FWZ7vYiqm4dk=,tag:JnczZnp+ubaIixSYmheShQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
