apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microbin-data
  namespace: microbin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
