apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skate-streamer-reciever-data
  namespace: skate-streamer-reciever
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Gi
