apiVersion: v1
kind: Secret
metadata:
    name: ghost-mysql-secret
    namespace: ghost
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:EOFuKyH+xSiGKdu8BQaMEGc+EKo/vixzVbuDww==,iv:13l50NiuFAcsi0E8WgAv2/YFjZQHZC6Nnc9kqOOO3GU=,tag:Vzu67b7jdmRb/MDkBXe7OQ==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:I0jvQFZj3QI=,iv:7NvAF4vPG00WIejRmtwhqFTMgWJyDeTq8W6UvlVrEmg=,tag:gdjsN9brXsuMQMEDos1nVQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:mI/fYocVD4NocUqKtXPMthS7/zFDO+bEZPiHpg==,iv:qPjN3ALXr8lpUen3QVUbl5zWQ51xTMCGSRikL2xrTj8=,tag:9sZMW/HcZ0j4Ntxfd4EOng==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:c1bfNnA=,iv:qIU2aOjX4YCE/GFzGzVCjUaUKtMNkcvSQrBus4e5D1Q=,tag:QiRiRG0BZ/YiZrR2EiRL+w==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZUREQTVVSFU1MmJKVWZE
            bFJIM2R2Rlg1SHVic2U4cHVYTzYyVEh2R3owCmRVNUJFUHl5N3JTY2JmSUd6eXlM
            MllhNmxGYTVYS0FrS0l2YSs2d2c3VUkKLS0tIGVvVEpWc2RsNHZRSWxQZFJLODlo
            ZGFIbENUZk54Vy9NZzhiNnhINHkxRUEKSt4Cs11EUAthnj50HbaxpgOByY1KflUt
            GXkNCyLqZKC6u2bSc9fPGp/nDjtpQtFjjUecBL0ZFEuEIKQe8v4OWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T15:42:16Z"
    mac: ENC[AES256_GCM,data:BudHXeRrc06DhNLAoiaPj+iTvf56NN8qSWfVGS2gXmzq5I25wJBcovsk+HgNSOR3YQnW1iCL8Rob0XUEdKESWP0f6n1B7ir0HAgVyhIjnbteRphEjQmZlOyqxO4jr61wmb28dQQ/lV1x4olgFYQSJ3BUT+EPxa1DCfvb7ZiOFFU=,iv:iz9kfeHb+3ENWdH8xO7Rmc82PcKXcSRvzLe0vznq5qU=,tag:cFpkAob1V13Y3k4YuoicEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
