apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-mysql-data
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
