apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-wireguard
  namespace: wg-easy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
