apiVersion: v1
kind: Service
metadata:
  name: sevtech
  namespace: sevtech
spec:
  type: ClusterIP
  selector:
    app: sevtech
  ports:
    - name: game
      port: 25565
      targetPort: 25565
      protocol: TCP
