apiVersion: v1
kind: Secret
metadata:
    name: maxmind-license
    namespace: logging
type: Opaque
stringData:
    account_id: ENC[AES256_GCM,data:oPynXvAq,iv:976a4r+hSOBzdTnptc/ezbREwNHNcNn6XbU1rlkznA0=,tag:vW1sXvbNAMPOHyIin1RtuQ==,type:str]
    license_key: ENC[AES256_GCM,data:by6WSZuWStm+VXRTqhuxko6IjBSdV2s8Od+HYAALoS+FT0PMmWTuMw==,iv:uTigPhOJX3pk8MYyp/USd1bTcw+wuSDyJNaexXBgEaw=,tag:rXyi3NtSmD4/dQTzPIxXlw==,type:str]
sops:
    age:
        - recipient: age1zxpvrp778wzdh73fq5k2yln24aechr8n69n66smtjvepd56q9g9sa0xw5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbG9ld1NZVkExaGQvM1BS
            cTdYemtjRTFyOWJQbHUvaklzSUYwR1RRbnlNCmRaWWJHbjNHME0zdWZONzNJRTZJ
            MmFIZ21BRTlqMG1RNnFyWGlyNkdzTzgKLS0tIFBITS9VTVRsU2JnditEa0kzV1Ex
            S3FJWVNkMUZXMTBHNDBsNjlJOFIwVDgKSNgIAHfoaa7h9ytR2T15fAzjcnx92+Rf
            eYDpOnT6sRNuXis1UIJqTkyOn158tGdCRaLsmsmK2kOyoIVJcu8VPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T20:08:36Z"
    mac: ENC[AES256_GCM,data:khf5sIxukab5va+NoEz90z24DUspiLgXpedQsL3vHDGtAnn+qAxIPzbzF8+Yo7TeFnoyzbnBea7rb56FcIc0Ui5dCJtf+v9omIWTktEoVhjCUKGHcHCCvcm0ZW/uBlDgXR0+ppvP68af4Jm7aiB3xQC5HfGZy25lSsWv9U3LPH4=,iv:CiF/vH4g0ZjNXPYB1zTIzKJylZYx7w3GcFJmZS8dJC0=,tag:3TsfKw4QMty8xt0VcA/zbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
